# https://taskfile.dev

version: '3'

vars:
  LOCAL_SERVICES: "mongodb"
  UP_CONTAINERS: "docker-compose up -d {{.LOCAL_SERVICES}}"
  STOP_CMD: "docker-compose down -v"
  RUN_CMD: "python3 code/entrypoint.py"
  COMPOSE_FILE: "COMPOSE_FILE=docker-compose.yml"
  PIP_FREEZE: "pip freeze > requirements.txt"
  PIP_INSTALL: "pip install -r requirements.txt"

tasks:
  default:
    cmds:
      - "{{.RUN_CMD}}"
    silent: true

  freeze:
    silent: false
    cmds:
      - "{{.PIP_FREEZE}}"

  install:
    silent: false
    cmds:
      - "{{.PIP_INSTALL}}"

  run:
    silent: false
    cmds:
      - "{{.UP_CONTAINERS}}"
      - "{{.RUN_CMD}}"

  stop:
    silent: false
    cmds:
      - "{{.STOP_CMD}}"

  restart: 
    silent: false
    cmds:
      - task stop
      - task run